### ISSUE TITLE
Messaging Window

### ISSUE THREAD

**Issue by anavgupta** [Alafazam/easy_chat#2]
- Implementing Padding Bottom for message- window

**Comment by Alafazam** [comment]
This is fixed. Using matrealise footer .

**Comment by anavgupta** [comment]
![screenshot from 2016-01-19 23-38-11](https://cloud.githubusercontent.com/assets/10281456/12427562/f958da7c-bf05-11e5-9b41-697a52ac639f.png)
![screenshot from 2016-01-19 23-38-20](https://cloud.githubusercontent.com/assets/10281456/12427563/f95f7468-bf05-11e5-8e85-a7cf7fe1eb77.png)
![screenshot from 2016-01-19 23-39-00](https://cloud.githubusercontent.com/assets/10281456/12427564/f969e164-bf05-11e5-8737-e7222072aa89.png)

It somehow improved, but still not fully fixed.

**Comment by Alafazam** [comment]
Now you check, that time server wasn't running latest version. :)

**Comment by Alafazam** [comment]
https://github.com/Alafazam/easy_chat/commit/c15fd3ad023bd0db8c1fb1072d9242acc52ec649 and https://github.com/Alafazam/easy_chat/commit/99b9e4ed07fc442d11ed683b485feede15a1a4b3 fixes it.
